name = "foyue-wenku"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "foyue-db"
database_id = "be0b21ab-4549-45bc-ac38-5f9e1864d061"

[[r2_buckets]]
binding = "R2_WENKU"
bucket_name = "jingdianwendang"
